resources:
- manifests
generatedResources: |-
  rm -rf rsa
  mkdir -p rsa
  ssh-keygen -b 2048 -t rsa -f rsa/key -q -N ""
  kubectl -n ci create secret generic rsa \
    --type=Opaque \
    --from-file rsa/key \
    --from-file rsa/key.pub \
    --dry-run=client -o json | jq -c
  rm -rf keys