apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ci-secrets-main-cluster-admin
subjects:
- kind: ServiceAccount
  name: cluster-admin
  namespace: ci-secrets-main
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
