apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: concourse-web
  namespace: ci
spec:
  virtualhost:
    fqdn: concourse.domain.tld
  routes:
  - conditions:
    - prefix: /
    services:
    - name: concourse-web
      port: 80