resources:
- bootstrap.yml
- ../../../kubernetes/concourse
- ../../../kubernetes/monitoring
vars:
- name: NAMESPACE
  value: master
- name: CLUSTER_HOST
  valueFromFile: ../config/domain
- name: TEST        # only here to validate that the assemble file in the
  value: set-in-dev # monitoring folder is not affected by this.
patches:
- target:
    kind: HTTPProxy
    metadata:
      name: concourse-web
  replacements:
  - path: spec.virtualhost.fqdn
    value: concourse.${CLUSTER_HOST}
- target:
    kind: HTTPProxy
    metadata:
      name: grafana
  replacements:
  - path: spec.virtualhost.fqdn
    value: grafana.${CLUSTER_HOST}
- target:
    kind: HTTPProxy
    metadata:
      name: prometheus
  replacements:
  - path: spec.virtualhost.fqdn
    value: prometheus.${CLUSTER_HOST}